### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/DATA'

### ISSUE THREAD

**Issue by steveyg** [MeioJane/CHR#10]
hi~

When I run this program with "bash  CHR/runme.sh"，the output in terminal is :

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yg/Desktop/workspace/CHR/CHR/CHR/CHR/main.py", line 110, in <module>
    main_ray()
  File "/home/yg/Desktop/workspace/CHR/CHR/CHR/CHR/main.py", line 83, in main_ray
    train_dataset = XrayClassification(args.data, 'train')
  File "/home/yg/Desktop/workspace/CHR/CHR/CHR/CHR/ray.py", line 95, in __init__
    os.makedirs(path_csv)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/DATA'

In fact , I have not folder named '/DATA'. 
What is the purpose of this folder？ And how can I use dataset(SIXray) in this project?

thx!

**Comment by MeioJane** [comment]
> hi~
> 
> When I run this program with "bash CHR/runme.sh"，the output in terminal is :
> 
> Traceback (most recent call last):
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/yg/Desktop/workspace/CHR/CHR/CHR/CHR/main.py", line 110, in
> main_ray()
> File "/home/yg/Desktop/workspace/CHR/CHR/CHR/CHR/main.py", line 83, in main_ray
> train_dataset = XrayClassification(args.data, 'train')
> File "/home/yg/Desktop/workspace/CHR/CHR/CHR/CHR/ray.py", line 95, in **init**
> os.makedirs(path_csv)
> File "/usr/lib/python3.6/os.py", line 210, in makedirs
> makedirs(head, mode, exist_ok)
> File "/usr/lib/python3.6/os.py", line 210, in makedirs
> makedirs(head, mode, exist_ok)
> File "/usr/lib/python3.6/os.py", line 210, in makedirs
> makedirs(head, mode, exist_ok)
> [Previous line repeated 2 more times]
> File "/usr/lib/python3.6/os.py", line 220, in makedirs
> mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/DATA'
> 
> In fact , I have not folder named '/DATA'.
> What is the purpose of this folder？ And how can I use dataset(SIXray) in this project?
> 
> thx!

You should give the correct path of csv file
